services:
  flask:
    container_name: fitnesstracker
    # image: chavias/fitnesstracker:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - TLS=${TLS}
      - SSL=${SSL}
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - MAIL_SERVER=${MAIL_SERVER}
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:latest
    container_name: mariadb_fitness
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis_fitness
    restart: unless-stopped

volumes:
  mariadb_data:
  
