[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FitnessTracker"
version = "0.0.1"
authors = [
  { name="Matías Chávez", email="matias.chavez@mail.ch" },
]
description = "A simple application to track your workouts"
readme = "Readme.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/chavias/FitnessTracker"
Issues = "https://github.com/chavias/FitnessTracker/issues"