"""Add User support

Revision ID: da3a7ddf960c
Revises: 
Create Date: 2025-02-25 11:51:02.162052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3a7ddf960c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    
    # Create default user to own existing data
    # op.execute("INSERT INTO users (id, username, email, password ,image_file) VALUES (1, 'default_user', 'default', 'default@example.com', 'default.jpg')")
    
    # Add nullable user_id column first
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Associate all existing templates with user id 1
    op.execute("UPDATE templates SET user_id = 1")
    
    # Now make the column non-nullable
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.create_foreign_key('fk_templates_user_id', 'users', ['user_id'], ['id'])
    
    # Same process for training_sessions
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Associate all existing sessions with user id 1
    op.execute("UPDATE training_sessions SET user_id = 1")
    
    # Now make the column non-nullable
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.create_foreign_key('fk_training_sessions_user_id', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_training_sessions_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_templates_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
